 const my_media_array = [
 {
  "episode number": "677",
  "publish date": "2016-02-10 8",
  "book title": "A World Of Talent",
  "book author": "Philip K. Dick",
  "story link on wikipedia": "http://en.wikipedia.org/wiki/A_World_of_Talent",
  "author wikipedia entry": "https://en.wikipedia.org/wiki/Philip_K._Dick",
  "pdf link 1": "AWorldOfTalentByPhilipK.Dick.pdf",
  "pdf page count 1": "42",
  "pdf country 1": "",
  "pdf info 1": "Galaxy Science Fiction, October 1954",
  "pdf link 2": "",
  "pdf page count 2": "",
  "pdf country 2": "",
  "pdf info 2": "",
  "pdf link 3": "",
  "pdf page count 3": "",
  "pdf country 3": "",
  "pdf info 3": "",
  "pdf link 4": "",
  "pdf page count 4": "",
  "pdf country 4": "",
  "pdf info 4": ""
 },
 {
  "episode number": "704",
  "publish date": "2016-02-10 8",
  "book title": "The Eyes Have It",
  "book author": "Philip K. Dick",
  "story link on wikipedia": "",
  "author wikipedia entry": "https://en.wikipedia.org/wiki/Philip_K._Dick",
  "pdf link 1": "TheEyesHaveItByPhilipK.Dick.pdf",
  "pdf page count 1": "5",
  "pdf country 1": "",
  "pdf info 1": "Science Fiction Stories, 1, 1953",
  "pdf link 2": "",
  "pdf page count 2": "",
  "pdf country 2": "",
  "pdf info 2": "",
  "pdf link 3": "",
  "pdf page count 3": "",
  "pdf country 3": "",
  "pdf info 3": "",
  "pdf link 4": "",
  "pdf page count 4": "",
  "pdf country 4": "",
  "pdf info 4": ""
 },
 {
  "episode number": "710",
  "publish date": "2016-02-10 8",
  "book title": "jam packed  Beyond Lies The Wub",
  "book author": "Philip K. Dick",
  "story link on wikipedia": "http://en.wikipedia.org/wiki/Beyond_Lies_the_Wub",
  "author wikipedia entry": "https://en.wikipedia.org/wiki/Philip_K._Dick",
  "pdf link 1": "BeyondLiesTheWubByPhilipK.Dick.pdf",
  "pdf page count 1": "6",
  "pdf country 1": "",
  "pdf info 1": "Planet Stories, July 1952",
  "pdf link 2": "",
  "pdf page count 2": "",
  "pdf country 2": "",
  "pdf info 2": "",
  "pdf link 3": "",
  "pdf page count 3": "",
  "pdf country 3": "",
  "pdf info 3": "",
  "pdf link 4": "",
  "pdf page count 4": "",
  "pdf country 4": "",
  "pdf info 4": ""
 }
]; module.exports = my_media_array;